# gws-connect installer for Windows. Meant to be run by Claude Code:
#   powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://github.com/chrisTeclead/gws-connect/releases/latest/download/install.ps1 | iex"
#
# Invoke-WebRequest sets no Mark of the Web, so nothing here meets SmartScreen.
# Everything lands in ~/.gws-connect/app; accounts and credentials are never
# touched. Running it again is how you update. It throws instead of exiting,
# so a user who pasted it into their own window keeps that window.
& {
  $ErrorActionPreference = 'Stop'
  $ProgressPreference = 'SilentlyContinue'
  # Windows PowerShell 5.1 may still default to TLS 1.0, which GitHub refuses.
  [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

  $release = if ($env:GWS_CONNECT_RELEASE_URL) { $env:GWS_CONNECT_RELEASE_URL } else { 'https://github.com/chrisTeclead/gws-connect/releases/latest/download' }
  $homeDir = if ($env:GWS_CONNECT_HOME) { $env:GWS_CONNECT_HOME } else { Join-Path $env:USERPROFILE '.gws-connect' }
  $claudeDir = if ($env:CLAUDE_CONFIG_DIR) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $env:USERPROFILE '.claude' }
  $prefix = 'gws-connect install failed:'

  $arch = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }
  if ($arch -eq 'ARM64') { throw "$prefix there is no ARM Windows build of gws" }
  if ($arch -ne 'AMD64') { throw "$prefix unsupported processor $arch" }
  $bundle = 'gws-connect-win-x64'

  New-Item -ItemType Directory -Force -Path $homeDir | Out-Null
  $work = Join-Path $homeDir ('.install-' + [guid]::NewGuid().ToString('N'))
  New-Item -ItemType Directory -Path $work | Out-Null
  try {
    Write-Host "downloading $bundle"
    $sums = Join-Path $work 'SHA256SUMS'
    $zip = Join-Path $work "$bundle.zip"
    try { Invoke-WebRequest -UseBasicParsing -Uri "$release/SHA256SUMS" -OutFile $sums } catch { throw "$prefix could not download SHA256SUMS" }
    try { Invoke-WebRequest -UseBasicParsing -Uri "$release/$bundle.zip" -OutFile $zip } catch { throw "$prefix could not download $bundle.zip" }

    $expected = Get-Content $sums | ForEach-Object {
      $parts = $_ -split '\s+'
      if ($parts[1] -eq "$bundle.zip") { $parts[0] }
    } | Select-Object -First 1
    if (-not $expected) { throw "$prefix SHA256SUMS lists no $bundle.zip" }
    $actual = (Get-FileHash -Algorithm SHA256 -LiteralPath $zip).Hash
    if ($actual -ne $expected) { throw "$prefix checksum mismatch for $bundle.zip - nothing was changed" }

    $unpacked = Join-Path $work 'unpacked'
    Expand-Archive -LiteralPath $zip -DestinationPath $unpacked
    $new = Join-Path $unpacked $bundle
    if (-not (Test-Path (Join-Path $new 'runtime\node\node.exe'))) { throw "$prefix $bundle.zip is incomplete" }

    # The old app is removed only once the new one is in place. A running
    # gws-connect locks node.exe, and the rename fails cleanly in that case.
    $app = Join-Path $homeDir 'app'
    $old = Join-Path $work 'old-app'
    if (Test-Path $app) {
      try { Move-Item -LiteralPath $app -Destination $old } catch { throw "$prefix gws-connect is still running - close its windows and try again" }
    }
    try { Move-Item -LiteralPath $new -Destination $app } catch {
      if (Test-Path $old) { Move-Item -LiteralPath $old -Destination $app }
      throw "$prefix could not move the new version into place"
    }

    # %~dp0 is the launcher's own folder. Nothing absolute is written, because
    # cmd.exe reads batch files in the OEM codepage and would mangle a user
    # name like "Anna Müller".
    $launcher = Join-Path $homeDir 'gws-connect.cmd'
    $body = @'
@echo off
rem Generated by install.ps1. Do not edit. Runs gws-connect from the installed app.
set "GWS_CONNECT_GWS_BIN=%~dp0app\runtime\gws\gws.exe"
"%~dp0app\runtime\node\node.exe" "%~dp0app\bin\gws-connect.mjs" %*
'@
    [IO.File]::WriteAllText($launcher, $body.Replace("`n", "`r`n").Replace("`r`r", "`r"), [Text.Encoding]::ASCII)

    & $launcher relink | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "$prefix could not repair the account launchers" }

    $skills = Join-Path $claudeDir 'skills'
    New-Item -ItemType Directory -Force -Path $skills | Out-Null
    $skill = Join-Path $skills 'gws-konten'
    if (Test-Path $skill) { Remove-Item -LiteralPath $skill -Recurse -Force }
    Copy-Item -LiteralPath (Join-Path $app 'skills\gws-konten') -Destination $skill -Recurse

    $version = (Get-Content -Raw (Join-Path $app 'package.json') | ConvertFrom-Json).version
    Write-Host "installed gws-connect $version - next: $launcher doctor --yes"
  } finally {
    Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue
  }
}
