#!/usr/bin/env bash
# gws-connect installer for macOS. Meant to be run by Claude Code:
#   curl -fsSL https://github.com/chrisTeclead/gws-connect/releases/latest/download/install.sh | bash
#
# curl sets no quarantine flag, so nothing here meets Gatekeeper. Everything
# lands in ~/.gws-connect/app; accounts and credentials are never touched.
# Running it again is how you update.
set -euo pipefail

RELEASE_URL="${GWS_CONNECT_RELEASE_URL:-https://github.com/chrisTeclead/gws-connect/releases/latest/download}"
HOME_DIR="${GWS_CONNECT_HOME:-$HOME/.gws-connect}"
SKILLS_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/skills"

fail () { echo "gws-connect install failed: $*" >&2; exit 1; }

[ "$(uname -s)" = "Darwin" ] || fail "this installer is for macOS; on Windows use install.ps1"

# A shell under Rosetta reports x86_64 on Apple Silicon. The hardware flag
# does not lie, and the native build is the one that should run.
if [ "$(sysctl -n hw.optional.arm64 2>/dev/null || echo 0)" = "1" ]; then
  PLATFORM=mac-arm64
elif [ "$(uname -m)" = "x86_64" ]; then
  PLATFORM=mac-x64
else
  fail "unsupported processor $(uname -m)"
fi
BUNDLE="gws-connect-$PLATFORM"

mkdir -p "$HOME_DIR"
WORK="$(mktemp -d "$HOME_DIR/.install-XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

echo "downloading $BUNDLE"
curl -fsSL -o "$WORK/SHA256SUMS" "$RELEASE_URL/SHA256SUMS" || fail "could not download SHA256SUMS"
curl -fsSL -o "$WORK/$BUNDLE.zip" "$RELEASE_URL/$BUNDLE.zip" || fail "could not download $BUNDLE.zip"

expected="$(awk -v f="$BUNDLE.zip" '$2 == f { print $1 }' "$WORK/SHA256SUMS")"
[ -n "$expected" ] || fail "SHA256SUMS lists no $BUNDLE.zip"
actual="$(shasum -a 256 "$WORK/$BUNDLE.zip" | awk '{ print $1 }')"
[ "$expected" = "$actual" ] || fail "checksum mismatch for $BUNDLE.zip - nothing was changed"

unzip -q "$WORK/$BUNDLE.zip" -d "$WORK/unpacked" || fail "could not unpack $BUNDLE.zip"
[ -x "$WORK/unpacked/$BUNDLE/runtime/node/bin/node" ] || fail "$BUNDLE.zip is incomplete"
xattr -dr com.apple.quarantine "$WORK/unpacked/$BUNDLE" 2>/dev/null || true

# The old app is removed only once the new one is in place.
APP="$HOME_DIR/app"
if [ -d "$APP" ]; then mv "$APP" "$WORK/old-app"; fi
if ! mv "$WORK/unpacked/$BUNDLE" "$APP"; then
  if [ -d "$WORK/old-app" ]; then mv "$WORK/old-app" "$APP"; fi
  fail "could not move the new version into place"
fi

LAUNCHER="$HOME_DIR/gws-connect"
cat > "$LAUNCHER" <<'EOF'
#!/usr/bin/env bash
# Generated by install.sh. Do not edit. Runs gws-connect from the installed app.
HERE="$(cd "$(dirname "$0")" && pwd)"
export GWS_CONNECT_GWS_BIN="$HERE/app/runtime/gws/gws"
exec "$HERE/app/runtime/node/bin/node" "$HERE/app/bin/gws-connect.mjs" "$@"
EOF
chmod 755 "$LAUNCHER"

"$LAUNCHER" relink >/dev/null || fail "could not repair the account launchers"

mkdir -p "$SKILLS_DIR"
rm -rf "$SKILLS_DIR/gws-konten"
cp -R "$APP/skills/gws-konten" "$SKILLS_DIR/gws-konten"

VERSION="$("$APP/runtime/node/bin/node" -p 'require(process.argv[1]).version' "$APP/package.json")"
echo "installed gws-connect $VERSION - next: $LAUNCHER doctor --yes"
