// One launcher per account. The launcher holds no secret and no logic - it
// hands off to bin/gws-run.mjs, which is the single place that turns a
// credential set into environment variables.
//
// The predecessor inlined the keychain read into every generated wrapper.
// That was tolerable on macOS but would force a .cmd file to do DPAPI
// decryption in batch script, and batch is the wrong place for cryptography.
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { binDir, ensureDir, platform } from './paths.mjs'

export function runnerPath () {
  return fileURLToPath(new URL('../../bin/gws-run.mjs', import.meta.url))
}

export function wrapperPath (id) {
  const suffix = platform() === 'win32' ? '.cmd' : ''
  return path.join(binDir(), `gws-${id}${suffix}`)
}

// In a bundle the gws binary sits next to the tool, not on the PATH. The
// launcher is a separate process started from anywhere, so it has to carry the
// path itself - the same way it already carries an absolute path to node.
function bundledGws () {
  return process.env.GWS_CONNECT_GWS_BIN || ''
}

function posixBody (id, runner) {
  const gws = bundledGws()
  return `#!/usr/bin/env bash
# Generated by gws-connect. Do not edit.
# Runs the Google Workspace CLI as exactly one account: ${id}
${gws ? `export GWS_CONNECT_GWS_BIN="${gws}"\n` : ''}exec "${process.execPath}" "${runner}" "${id}" -- "$@"
`
}

function windowsBody (id, runner) {
  const gws = bundledGws()
  return `@echo off
rem Generated by gws-connect. Do not edit.
rem Runs the Google Workspace CLI as exactly one account: ${id}
${gws ? `set "GWS_CONNECT_GWS_BIN=${gws}"\n` : ''}"${process.execPath}" "${runner}" "${id}" -- %*
`
}

export async function write (id) {
  await ensureDir(binDir())
  const file = wrapperPath(id)
  const runner = runnerPath()
  const win = platform() === 'win32'
  await fs.writeFile(file, win ? windowsBody(id, runner) : posixBody(id, runner), {
    mode: win ? 0o600 : 0o700
  })
  if (!win) await fs.chmod(file, 0o700)
  return file
}

export async function removeFor (id) {
  await fs.rm(path.join(binDir(), `gws-${id}`), { force: true })
  await fs.rm(path.join(binDir(), `gws-${id}.cmd`), { force: true })
}
